import type { Tour } from '../search/types'

export const mockTours: Tour[] = [
  {
    id: 't1',
    slug: 'gobi-desert-camel-trek',
    destinationSlug: 'gobi-desert',
    hostSlug: 'gobi-adventure-tours',
    title: 'Gobi Desert Camel Trek',
    location: 'Gobi Desert',
    region: 'Gobi Region',
    regionSlug: 'gobi',
    price: 420,
    duration: '4 days',
    durationDays: 4,
    rating: 4.9,
    reviewCount: 128,
    maxGuests: 10,
    groupSize: 'small',
    style: 'adventure',
    experienceTypes: ['extreme', 'wildlife'],
    images: ['https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=800'],
    shortDescription: 'Trek across golden dunes with Bactrian camels and sleep under a billion stars.',
    highlights: ['Khongoryn Els sand dunes', 'Flaming Cliffs at sunset', 'Traditional ger camp stay', 'Local nomadic family visit'],
    included: ['Guide', 'Meals', 'Accommodation', 'Camel rides'],
    available: true,
  },
  {
    id: 't2',
    slug: 'lake-khovsgol-horseback-expedition',
    destinationSlug: 'lake-khovsgol',
    hostSlug: 'northern-trails',
    title: 'Lake Khövsgöl Horseback Expedition',
    location: 'Lake Khövsgöl',
    region: 'Northern Mongolia',
    regionSlug: 'khuvsgul',
    price: 680,
    duration: '7 days',
    durationDays: 7,
    rating: 4.8,
    reviewCount: 94,
    maxGuests: 8,
    groupSize: 'small',
    style: 'trekking',
    experienceTypes: ['horseback', 'extreme', 'wildlife'],
    images: ['https://images.unsplash.com/photo-1549880338-65ddcdfd017b?w=800'],
    shortDescription: 'Ride along Mongolia\'s deepest lake through ancient taiga forests.',
    highlights: ['Horseback riding along shoreline', 'Tsaatan reindeer herder visit', 'Crystal-clear lake kayaking', 'Wildflower meadows'],
    included: ['Guide', 'Horses', 'Meals', 'Camping gear'],
    available: true,
  },
  {
    id: 't3',
    slug: 'ulaanbaatar-city-culture-day',
    destinationSlug: 'ulaanbaatar',
    hostSlug: 'ub-culture-tours',
    title: 'Ulaanbaatar City & Culture Day',
    location: 'Ulaanbaatar',
    region: 'Central Mongolia',
    regionSlug: 'ulaanbaatar',
    price: 85,
    duration: '1 day',
    durationDays: 1,
    rating: 4.6,
    reviewCount: 210,
    maxGuests: 15,
    groupSize: 'group',
    style: 'cultural',
    experienceTypes: ['cultural'],
    images: ['https://images.unsplash.com/photo-1596178060671-7a80dc8059ea?w=800'],
    shortDescription: 'Discover Mongolian history, Buddhist temples, and vibrant street food scene.',
    highlights: ['Gandantegchinlen Monastery', 'National Museum of Mongolia', 'Narantuul Black Market', 'Traditional lunch'],
    included: ['Guide', 'Lunch', 'Museum entry'],
    available: true,
  },
  {
    id: 't4',
    slug: 'orkhon-valley-nomadic-life',
    destinationSlug: 'orkhon-valley',
    hostSlug: 'steppe-riders',
    title: 'Orkhon Valley Nomadic Life',
    location: 'Orkhon Valley',
    region: 'Central Mongolia',
    regionSlug: 'khangai',
    price: 550,
    duration: '5 days',
    durationDays: 5,
    rating: 4.7,
    reviewCount: 76,
    maxGuests: 8,
    groupSize: 'small',
    style: 'cultural',
    experienceTypes: ['nomadic', 'cultural'],
    images: ['https://images.unsplash.com/photo-1551632811-561732d1e306?w=800'],
    shortDescription: 'Live with nomadic herder families in the UNESCO World Heritage Orkhon Valley.',
    highlights: ['Ger stay with nomadic family', 'Traditional cheese making', 'Orkhon waterfall hike', 'Ancient Turkic ruins'],
    included: ['Guide', 'Accommodation', 'All meals', 'Transport'],
    available: true,
  },
  {
    id: 't5',
    slug: 'terelj-weekend-escape',
    destinationSlug: 'terelj',
    hostSlug: 'steppe-riders',
    title: 'Terelj Weekend Escape',
    location: 'Terelj National Park',
    region: 'Central Mongolia',
    regionSlug: 'steppe',
    price: 195,
    duration: '2 days',
    durationDays: 2,
    rating: 4.5,
    reviewCount: 183,
    maxGuests: 12,
    groupSize: 'group',
    style: 'adventure',
    experienceTypes: ['extreme', 'nomadic', 'horseback'],
    images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
    shortDescription: 'A perfect weekend getaway just 55km from the capital – granite peaks and lush meadows.',
    highlights: ['Turtle Rock hike', 'Ger camp bonfire', 'Archery & horse riding', 'Ariyabal Meditation Temple'],
    included: ['Transport from UB', 'Guide', 'Ger accommodation', 'Meals'],
    available: true,
  },
  {
    id: 't6',
    slug: 'altai-eagle-hunter-expedition',
    destinationSlug: 'altai-mountains',
    hostSlug: 'altai-expeditions',
    title: 'Altai Eagle Hunter Expedition',
    location: 'Altai Mountains',
    region: 'Western Mongolia',
    regionSlug: 'altai',
    price: 1280,
    duration: '10 days',
    durationDays: 10,
    rating: 5.0,
    reviewCount: 32,
    maxGuests: 6,
    groupSize: 'private',
    style: 'photography',
    experienceTypes: ['extreme', 'cultural', 'wildlife'],
    images: ['https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=800'],
    shortDescription: 'Join Kazakh eagle hunters in the remote Altai and capture once-in-a-lifetime photographs.',
    highlights: ['Eagle hunter home stay', 'Golden Eagle Festival', 'High mountain trekking', 'Rare wildlife spotting'],
    included: ['Private guide', 'All accommodation', 'All meals', 'Domestic flights'],
    available: true,
  },
  {
    id: 't7',
    slug: 'luxury-mongolia-grand-tour',
    destinationSlug: 'gobi-desert',
    hostSlug: 'gobi-adventure-tours',
    title: 'Luxury Mongolia Grand Tour',
    location: 'Gobi Desert',
    region: 'Gobi Region',
    regionSlug: 'gobi',
    price: 1850,
    duration: '14 days',
    durationDays: 14,
    rating: 4.9,
    reviewCount: 22,
    maxGuests: 6,
    groupSize: 'private',
    style: 'luxury',
    experienceTypes: ['luxury'],
    images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800'],
    shortDescription: 'Experience the best of Mongolia in premium luxury lodges from the Gobi to the north.',
    highlights: ['Three Camel Lodge', 'Private helicopter rides', 'Fine dining & spa', 'Expert naturalist guides'],
    included: ['Private guide & driver', 'Luxury lodges', 'All meals', 'Domestic flights', 'Airport transfers'],
    available: true,
  },
  {
    id: 't8',
    slug: 'budget-gobi-discovery',
    destinationSlug: 'gobi-desert',
    hostSlug: 'gobi-adventure-tours',
    title: 'Budget Gobi Discovery',
    location: 'Gobi Desert',
    region: 'Gobi Region',
    regionSlug: 'gobi',
    price: 240,
    duration: '3 days',
    durationDays: 3,
    rating: 4.3,
    reviewCount: 145,
    maxGuests: 16,
    groupSize: 'group',
    style: 'budget',
    experienceTypes: ['extreme', 'wildlife'],
    images: ['https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800'],
    shortDescription: 'Explore the iconic Gobi Desert on a budget without missing the highlights.',
    highlights: ['Khongoryn Els dunes', 'Yolyn Am canyon', 'Bayanzag Flaming Cliffs', 'Dinosaur fossil site'],
    included: ['Shared 4WD', 'Guide', 'Ger accommodation', 'Meals'],
    available: true,
  },
  {
    id: 't9',
    slug: 'naadam-festival-special',
    destinationSlug: 'ulaanbaatar',
    hostSlug: 'ub-culture-tours',
    title: 'Naadam Festival Special',
    location: 'Ulaanbaatar',
    region: 'Central Mongolia',
    regionSlug: 'ulaanbaatar',
    price: 320,
    duration: '3 days',
    durationDays: 3,
    rating: 4.8,
    reviewCount: 98,
    maxGuests: 20,
    groupSize: 'group',
    style: 'cultural',
    experienceTypes: ['cultural', 'nomadic'],
    images: ['https://images.unsplash.com/photo-1527004013197-933b6523d48e?w=800'],
    shortDescription: 'Attend Mongolia\'s greatest national festival with VIP seating and cultural events.',
    highlights: ['Naadam Stadium VIP seats', 'Archery & wrestling contests', 'Horserace at Khui Doloon Khudag', 'Traditional costumes'],
    included: ['Festival tickets', 'Hotel accommodation', 'Guide', 'Airport transfers'],
    available: true,
  },
  {
    id: 't10',
    slug: 'khentii-wolf-wildlife-safari',
    destinationSlug: 'eastern-mongolia',
    hostSlug: 'steppe-riders',
    title: 'Khentii Wolf & Wildlife Safari',
    location: 'Khentii Province',
    region: 'Eastern Mongolia',
    regionSlug: 'steppe',
    price: 890,
    duration: '6 days',
    durationDays: 6,
    rating: 4.7,
    reviewCount: 41,
    maxGuests: 8,
    groupSize: 'small',
    style: 'adventure',
    experienceTypes: ['wildlife', 'extreme'],
    images: ['https://images.unsplash.com/photo-1440342359743-84fcb8c21f21?w=800'],
    shortDescription: 'Track wolves and spot Mongolian gazelle across the pristine steppe of Genghis Khan\'s homeland.',
    highlights: ['Wildlife tracking with expert guide', 'Birthplace of Genghis Khan', 'Remote river camping', 'Steppe prairie ecosystems'],
    included: ['Expert naturalist guide', 'Camping gear', 'Meals', '4WD transport'],
    available: true,
  },
]
